"""empty message

Revision ID: 369c0c8c782c
Revises: 4ec5828a34b4
Create Date: 2025-02-26 21:59:59.840974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369c0c8c782c'
down_revision = '4ec5828a34b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_constraint('empresa_nombre_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.create_unique_constraint('empresa_nombre_key', ['nombre'])

    # ### end Alembic commands ###
